name: Gradle check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Build
        run: |
          ./gradlew :app:assembleDebug
      - name : upload apk
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: Neoterm-Debug
          path: ${{ github.workspace }}/app/build/outputs/apk/debug
